(import ./helper :prefix "")

(start-suite)

# Construction

(def v (vector 1 2 3))
(assert (= :core/vector (type v)) "a vector is a core/vector")
(assert (= 3 (length v)) "vector length")
(assert (= 0 (length (vector))) "empty vector length")
(assert (= (vector 1 2 3) (vec [1 2 3])) "vec of a tuple")
(assert (= (vector 1 2 3) (vec @[1 2 3])) "vec of an array")
(assert (= v (vec v)) "vec of a vector")
(assert (= 1000 (length (vec (range 1000)))) "vec of a long array")
(assert-error "vec refuses a string" (vec "abc"))
(assert-error "vec refuses a table" (vec @{}))

# Reading

(def big (vec (range 1000)))
(assert (= 1 (get v 0)) "get")
(assert (= 999 (get big 999)) "get past the first leaf")
(assert (nil? (get v 3)) "get past the end")
(assert (nil? (get v -1)) "get a negative index")
(assert (nil? (get v :a)) "get a keyword")
(assert (= 2 (in v 1)) "in")
(assert-error "in past the end" (in v 3))
(assert (indexed? v) "a vector is indexed")
(assert (not (bytes? v)) "a vector is not bytes")
(assert (= [1 2 3] (tuple ;v)) "splice")
(assert (= 6 (+ ;v)) "splice into a call")
(assert (deep= @[2 3 4] (map inc v)) "map")
(assert (= [0 1 2] (take 3 big)) "take")
(assert (= [998 999] (drop 998 big)) "drop")
(assert (= [997 998 999] (tuple/slice big 997)) "tuple/slice")
(assert (deep= @[31 32 33] (array/slice big 31 34)) "array/slice across a leaf")
(assert (= 499500 (sum big)) "sum")
(assert (= "1,2,3" (string/join (map string v) ",")) "string/join")
(let [[a b] v] (assert (= [1 2] [a b]) "destructuring"))
(assert (= 3 (match v [_ _ c] c)) "match")
(def seen @[])
(each x big (array/push seen x))
(assert (deep= (range 1000) seen) "each")
(assert (deep= @[0 1 2] (array/concat @[] (vector 0 1 2))) "array/concat")

# Updating

(def w (conj v 4 5))
(assert (= (vector 1 2 3 4 5) w) "conj several")
(assert (= (vector 1 2 3) v) "conj leaves the original")
(assert (= (vector 1 :x 3) (assoc v 1 :x)) "assoc")
(assert (= (vector 1 2 3 4) (assoc v 3 4)) "assoc at the length appends")
(assert (= (vector :a :b 3) (assoc v 0 :a 1 :b)) "assoc several")
(assert (= (vector 1 2 3) v) "assoc leaves the original")
(def big2 (assoc big 500 :x))
(assert (= 500 (get big 500)) "assoc in the trie leaves the original")
(assert (= :x (get big2 500)) "assoc in the trie")
(assert-error-value "assoc past the length"
  "index 5 out of range for vector of length 3" (assoc v 5 0))
(assert-error "assoc a negative index" (assoc v -1 0))
(assert-error "assoc a keyword" (assoc v :a 0))
(assert-error "assoc a dangling key" (assoc v 0 1 2))
(assert-error "conj a tuple" (conj [1] 2))
(assert-error "conj nil" (conj nil 2))

(var grown (vector))
(for i 0 5000 (set grown (conj grown i)))
(gccollect)
(assert (= (vec (range 5000)) grown) "conj one at a time")

# Transients

(def base (vector 1 2 3))
(def tr (transient base))
(assert (= :core/transient (type tr)) "a transient is a core/transient")
(assert (= tr (conj! tr 4 5)) "conj! returns the transient")
(assert (= tr (assoc! tr 0 :a 5 6)) "assoc! returns the transient")
(assert (= 6 (length tr)) "transient length")
(assert (= :a (get tr 0)) "transient get")
(assert (= 6 (in tr 5)) "transient in")
(assert (nil? (get tr 6)) "transient get past the end")
(assert-error "transient in past the end" (in tr 6))
(assert (not (indexed? tr)) "a transient is not indexed")
(assert-error "splice a transient" (tuple ;tr))
(assert-error "map a transient" (map inc tr))
(assert-error "each over a transient" (each _ tr))
(assert-error "keys of a transient" (keys tr))
(assert-error-value "assoc! past the length"
  "index 9 out of range for vector of length 6" (assoc! tr 9 0))
(assert-error "transient of a transient" (transient tr))
(assert-error "transient of a tuple" (transient [1 2]))
(assert-error "conj! a vector" (conj! base 4))
(def persisted (persistent! tr))
(assert (= (vector :a 2 3 4 5 6) persisted) "persistent!")
(assert (= (vector 1 2 3) base) "a transient leaves its vector")
(assert-error-value "conj! after persistent!"
  "transient used after persistent!" (conj! tr 7))
(assert-error "assoc! after persistent!" (assoc! tr 0 7))
(assert-error "length after persistent!" (length tr))
(assert-error "get after persistent!" (get tr 0))
(assert-error "persistent! twice" (persistent! tr))
(def again (transient persisted))
(assoc! again 1 :b)
(assert (= (vector :a 2 3 4 5 6) persisted)
  "a second transient leaves the first's vector")

(def batch (transient (vector)))
(for i 0 5000 (conj! batch i))
(gccollect)
(for i 0 5000 (assoc! batch i (* 2 i)))
(def doubled (persistent! batch))
(assert (= (vec (map |(* 2 $) (range 5000))) doubled) "a long batch")
(assert (= (hash (vec (map |(* 2 $) (range 5000)))) (hash doubled))
  "a batch hashes as the vector it equals")

# Equality, order and hash

(assert (= (vector) (vector)) "empty vectors are equal")
(assert (not= (vector 1 2) (vector 1 3)) "unequal elements")
(assert (not= (vector 1 2) (vector 1 2 3)) "unequal lengths")
(assert (not= (vector 1 2) [1 2]) "a vector is not a tuple")
(def t @{})
(assert (= (vector [1 2] t) (vector [1 2] t)) "elements compare as values")
(assert (not= (vector @{}) (vector @{})) "tables compare by identity")
(assert (= (hash grown) (hash (vec (range 5000)))) "equal vectors hash alike")
(assert (= :found (get {(vector 1 2) :found} (vector 1 2))) "a vector as a struct key")
(assert (= :found (get @{(vec (range 40)) :found} (vec (range 40))))
  "a vector as a table key")
(assert (= -1 (cmp (vector 1 2) (vector 1 3))) "order by element")
(assert (= -1 (cmp (vector 1 2) (vector 1 2 0))) "a prefix orders first")
(assert (deep= @[(vector) (vector 0 9) (vector 1)]
               (sort @[(vector 1) (vector) (vector 0 9)])) "sort")

# Marshalling

(defn round-trip [x] (unmarshal (marshal x)))
(assert (= v (round-trip v)) "marshal a vector")
(assert (= (vector) (round-trip (vector))) "marshal an empty vector")
(assert (= big (round-trip big)) "marshal a long vector")
(assert (= :core/vector (type (round-trip v))) "a marshalled vector is a vector")
(assert (= (hash grown) (hash (round-trip grown))) "a marshalled vector hashes alike")
(def mixed (vector 1.5 "s" :k 'sym @[1] {:a 1} [1 2] (vector (vector 3))))
(def mixed-back (round-trip mixed))
(assert (= 8 (length mixed-back)) "marshal mixed elements")
(assert (deep= @[1] (get mixed-back 4)) "marshal an array element")
(assert (= (vector (vector 3)) (get mixed-back 7)) "marshal nested vectors")
(def pair (round-trip @[v v]))
(assert (= (in pair 0) (in pair 1)) "a vector marshalled twice")
(def cyc @{})
(def holder (vector cyc))
(put cyc holder :found)
(def holder-back (round-trip holder))
(assert (= :found (get (in holder-back 0) holder-back))
  "a vector used as a key in its own element")
(assert (= (vector :a 2 3 4 5 6) (round-trip persisted))
  "marshal a vector a transient made")
(assert-error "marshal a transient" (marshal (transient v)))

# Printing

(assert (= "<core/vector 1 2 3>" (describe v)) "describe")
(assert (= "<core/vector 1 \"a\" :b <core/vector 2>>"
           (describe (vector 1 "a" :b (vector 2)))) "describe nested")
(assert (= "<core/vector 1 2 3>" (string/format "%q" v)) "format")

(end-suite)
