#!/usr/bin/env janet
# The two arms of every benchmark corpus, and whether they are the same
# program.
#
#     ./res/check/bench-arms.janet           regenerate res/check/bench-arms.txt
#     ./res/check/bench-arms.janet --check   fail if the tree disagrees with it
#
# ## Why this exists
#
# C Janet cannot read a `.wattle` file, so measuring Wattle against it needs
# each workload in both syntaxes: `res/bench/<stem>.janet` run by the Janet
# binary and `res/bench/<stem>.wattle` run by the Wattle one. Two files that
# are meant to be the same program drift, and a ratio between two arms that
# have drifted is worse than no ratio, because it looks like a result.
#
# What makes this checkable rather than a matter of care is that the `.wattle`
# arm was not written: `res/repo/janet-to-wattle.janet` produced it from the
# `.janet` arm at the swap. So the equivalence can be *derived* -- run the
# converter again and compare -- instead of asserted. A hand edit to either
# side shows up here on the next run.
#
# ## What a difference means
#
# The converter is lexical and every substitution is one form for one form, so
# a difference in the forms is a difference in the program and the ratio built
# on it is void. A difference in a *comment* is not: step 6 rewrote path
# references by hand, so the `.janet` arm says `sizes.janet` where the
# `.wattle` arm says `sizes.wattle`, and each is right about its own world.
# Those are recorded in the list beside this file rather than suppressed, so
# that a new one has to be looked at.
#
# ## Why the converter is not run against the tree
#
# It writes the `.wattle` file beside its input, which would overwrite the arm
# being checked. Each `.janet` arm is copied into a scratch directory under
# `zig-out`, which is gitignored, and converted there.

(import ../common :as tools)

(def- list-path "res/check/bench-arms.txt")
(def- scratch "zig-out/bench-arms")

(defn- stems
  "Every corpus with a `.janet` arm, as a stem under `res/bench/`."
  []
  (def out @[])
  (defn walk [dir]
    (each entry (sort (os/dir dir))
      (def path (string dir "/" entry))
      (case (os/stat path :mode)
        :directory (walk path)
        :file (when (string/has-suffix? ".janet" entry)
                (array/push out (string/slice path (length "res/bench/")
                                              (- (length path) (length ".janet"))))))))
  (walk "res/bench")
  (sort out))

(defn- differences
  "The lines on which the converter's output and the checked-in arm differ."
  [stem]
  (def src (string "res/bench/" stem ".janet"))
  (def dest (string scratch "/" stem ".janet"))
  (os/execute ["mkdir" "-p" (string scratch "/" (string/join
                                                  (slice (string/split "/" stem) 0 -2) "/"))] :p)
  (spit dest (slurp src))
  (def result (tools/sh (string "./res/repo/janet-to-wattle.janet " dest)))
  (unless (tools/ok? result)
    (tools/die (string "the converter refused " src)))
  (def produced (string/split "\n" (slurp (string scratch "/" stem ".wattle"))))
  (def checked-in (string/split "\n" (slurp (string "res/bench/" stem ".wattle"))))
  (def out @[])
  (var i 0)
  (while (or (< i (length produced)) (< i (length checked-in)))
    (def a (get produced i ""))
    (def b (get checked-in i ""))
    (unless (= a b)
      (array/push out [(inc i) a b]))
    (++ i))
  out)

(defn main [& argv]
  (def check (has-value? argv "--check"))
  (os/cd tools/root)
  (tools/rm-rf scratch)

  (def rows @[])
  (each stem (stems)
    (array/push rows [stem (differences stem)]))

  (def lines @[])
  (array/push lines "# The two arms of each benchmark corpus.  Generated by")
  (array/push lines "# `./res/check/bench-arms.janet`; do not edit.")
  (array/push lines "#")
  (array/push lines "# Each row is a corpus whose `.wattle` arm is compared against what")
  (array/push lines "# `res/repo/janet-to-wattle.janet` produces from its `.janet` arm.  `same`")
  (array/push lines "# means the two are the same program by derivation rather than by assertion.")
  (array/push lines "#")
  (array/push lines "# A difference in a form voids any ratio measured over that corpus.  A")
  (array/push lines "# difference in a comment does not, and the two known ones are path")
  (array/push lines "# references each arm is right about in its own world.")
  (array/push lines "#")
  (array/push lines (string "# " (length rows) " corpora, "
                            (length (filter |(empty? (get $ 1)) rows)) " with identical arms"))
  (array/push lines "#")
  (array/push lines "# columns: corpus  state, then one indented line per differing line")
  (array/push lines "")
  (each [stem diffs] rows
    (array/push lines (string/format "%-20s %s" stem (if (empty? diffs) "same"
                                                       (string (length diffs) " differing"))))
    (each [n a b] diffs
      (array/push lines (string/format "    %4d janet-> %s" n a))
      (array/push lines (string/format "    %4d wattle> %s" n b))))
  (def text (string (string/join lines "\n") "\n"))

  (tools/rm-rf scratch)
  (if check
    # `slurp` answers with a buffer, and a buffer never equals a string however
    # its bytes read, so the comparison is made between two strings.
    (let [stored (string (slurp list-path))]
      (if (= stored text)
        (do (print (length rows) " corpora, "
                   (length (filter |(empty? (get $ 1)) rows)) " with identical arms")
            (os/exit 0))
        (do (eprint "res/check/bench-arms.txt disagrees with the tree:")
            # Zipping the two would stop at the shorter and hide a row added
            # at the end, which is the difference a new corpus makes.
            (let [o (string/split "\n" stored) n (string/split "\n" text)]
              (for i 0 (max (length o) (length n))
                (def a (get o i "")) (def b (get n i ""))
                (unless (= a b)
                  (eprint "  stored: " a)
                  (eprint "  now:    " b))))
            (os/exit 1))))
    (do
      (spit list-path text)
      (print "wrote " list-path " -- " (length rows) " corpora, "
             (length (filter |(empty? (get $ 1)) rows)) " with identical arms")
      (os/exit 0))))
