#!/usr/bin/env janet
# Which seam symbols every configuration exports, measured rather than derived.
#
# Phase 12 increment 5d's remainder. `convert.janet` refuses to convert a call
# site whose definition some configuration does not compile -- rule 28, because
# an `@import` pulls a file's `export fn` into the compilation and an
# `export fn` is emitted for being there rather than for being called, so the
# import breaks `-Dev=false` rather than the default build.
#
# ## Why this is measured
#
# The tool answered that question by reading `root.zig`'s `comptime` block, and
# the block does not name every file it compiles. `ev.zig`, `ev/stream.zig`,
# `ev/channel.zig`, `ev/backend.zig` and `pp.zig` are absent from it and are
# compiled anyway, because a file that *is* in the block imports and calls
# them: `env.zig` reaches `ev.zig`, `pp/format.zig` reaches `pp.zig`. The
# block's own header says so in prose -- "subsystems reached through the file
# that registers them" -- and prose is not something a tool can follow.
#
# Deriving it properly means walking the import graph while tracking which
# branches are comptime-live, and then knowing that root.zig's `pub const`
# block is deliberately *lazy* and compiles nothing. That is a static analysis
# of Zig, in Janet, to answer a question the linker answers exactly.
#
# So: build the configurations, read the symbol tables, write down what is
# missing. Rule 18 -- a derivation reproduced by inspection needs an oracle --
# and here the oracle is cheaper than the derivation.
#
# ## Rule 1, which cost a wrong finding
#
# The first sweep ran ten option configurations on this 64-bit host and
# reported `janet_nanbox32_from_tagi` and `janet_nanbox32_from_tagp` as
# exported by *nothing*, which read as two dead exports and a contract function
# that could never run. They are the 32-bit NaN-boxed layout's, and
# `value_repr` follows the target's pointer width. **The gate axis is not only
# `-D` options; the target is one too.** `x86-linux-musl` exports both.
#
#     ./tools/check/gates.janet           regenerate tools/check/gated.txt
#     ./tools/check/gates.janet --check   fail if the tree disagrees with it

(import ../common :as tools)

(def list-path "tools/check/gated.txt")
(def cache "/tmp/janet-gates-cache")
(def prefix "/tmp/janet-gates-out")

# The sweep. Each entry is [tag, flags]. The set is `tools/testing/matrix.janet`'s
# reduced configurations plus the two the *target* decides -- a 32-bit build
# for `nanbox_32` and a tagged one for the layout with no NaN box at all.
(def configs
  [["default" []]
   ["no-ev" ["-Dev=false"]]
   ["no-net" ["-Dnet=false"]]
   ["no-peg" ["-Dpeg=false"]]
   ["no-assembler" ["-Dassembler=false"]]
   ["no-int-types" ["-Dint-types=false"]]
   ["no-ffi" ["-Dffi=false"]]
   ["no-filewatch" ["-Dfilewatch=false"]]
   ["reduced-os" ["-Dreduced-os=true"]]
   ["single-threaded" ["-Dsingle-threaded=true"]]
   ["no-processes" ["-Dprocesses=false"]]
   ["tagged" ["-Dnanbox=false"]]
   ["x86-linux-musl" ["-Dtarget=x86-linux-musl"]]])

(defn- symbols-for
  "The exported symbols of the library `flags` builds, as a set."
  [tag flags]
  (def out (string prefix "/" tag))
  (def cmd (string "zig build " (string/join flags " ")
                   " --cache-dir " cache " -p " out))
  (def built (tools/sh cmd :timeout 900))
  (unless (zero? (or (built :code) 1))
    (tools/die tag ": build failed -- " cmd "\n" (string (built :err))))
  (def lib (find |(os/stat $ :mode)
                 [(string out "/lib/libjanet.dylib") (string out "/lib/libjanet.so")]))
  (unless lib (tools/die tag ": built no shared library under " out "/lib"))
  (def nm (string "nm -g " lib " | awk '$2 ~ /^[TDBSR]$/ {print $3}' | sed 's/^_//' | sort -u"))
  (def res (tools/sh nm :timeout 120))
  (unless (zero? (res :code)) (tools/die tag ": " nm " failed"))
  (def set @{})
  (each s (string/split "\n" (string/trim (string (res :out))))
    (unless (empty? s) (put set s true)))
  set)

(defn measure
  "symbol -> the tags whose build does not export it."
  []
  (os/execute ["rm" "-rf" cache prefix] :p)
  (def per @{})
  (each [tag flags] configs
    (eprint "  building " tag " ...")
    (put per tag (symbols-for tag flags)))
  (os/execute ["rm" "-rf" cache prefix] :p)
  # Every symbol any configuration publishes; a name absent from one of them
  # is what the caller may not `@import`.
  (def all @{})
  (eachp [_ set] per (eachk s set (put all s true)))
  (def out @{})
  (eachk s all
    (def missing (sort (filter |(not (get (per $) s)) (map first configs))))
    (unless (empty? missing) (put out s missing)))
  out)

(defn render [gated]
  (def out @"")
  (buffer/push out
    "# Symbols some configuration does not export.  Generated by\n"
    "# `./tools/check/gates.janet`; do not edit.\n"
    "#\n"
    "# `convert.janet` refuses a name listed here: an `@import` pulls a file's\n"
    "# `export fn` into the compilation whether or not it is called, so pointing\n"
    "# a call site at one breaks the configuration that leaves it out rather\n"
    "# than the default build.  Phase 12 rule 28.\n"
    "#\n"
    "# Measured over the configurations below, and **over nothing else** --\n"
    "# rule 1.  The target is a gate axis as much as a `-D` option is:\n"
    "# `value_repr` follows the pointer width, so the 32-bit entry is what\n"
    "# keeps the two `nanbox32` symbols off this list's dead-code reading.\n"
    "#\n")
  (each [tag flags] configs
    (buffer/push out (string/format "#   %-16s %s\n" tag (string/join flags " "))))
  (buffer/push out "#\n")
  (buffer/push out (string/format "# gated symbols  %d\n#\n\n" (length gated)))
  (each s (sort (keys gated))
    (buffer/push out (string/format "%-40s %s\n" s (string/join (gated s) " "))))
  (string out))

(defn parse
  "The names in a rendered list, as a set."
  [text]
  (def out @{})
  (each line (string/split "\n" text)
    (def t (string/trim line))
    (unless (or (empty? t) (string/has-prefix? "#" t))
      (put out (first (string/split " " t)) true)))
  out)

(defn gated-names
  "The checked-in list, as a set.  What `convert.janet` reads."
  []
  (parse (slurp list-path)))

(defn main [& argv]
  (os/cd tools/root)
  (def check (has-value? argv "--check"))
  (def gated (measure))
  (def text (render gated))
  (if check
    (do
      (def old (parse (slurp list-path)))
      (def new (parse text))
      (def arrived (sort (filter |(nil? (get old $)) (keys new))))
      (def departed (sort (filter |(nil? (get new $)) (keys old))))
      (each s departed (print "ungated  " s))
      (each s arrived (eprint "NEW GATE " s))
      (when (and (empty? arrived) (empty? departed))
        (print "the tree and " list-path " agree"))
      (os/exit (if (empty? arrived) 0 1)))
    (do
      (spit list-path text)
      (print "wrote " list-path " -- " (length gated) " gated symbols")
      (os/exit 0))))
